# Generated by Django 3.0.8 on 2020-09-17 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField(verbose_name='回答の本文')),
                ('is_best', models.BooleanField(default=False, verbose_name='ベストアンサー')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='回答した日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField(verbose_name='回答への返答')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='返答した日時')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Answer', verbose_name='対象の回答')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='返答者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', markdownx.models.MarkdownxField(verbose_name='質問の本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='質問した日時')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開する')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('not_answered', '未回答'), ('accepted', '解決済み')], default='not_answered', max_length=12, verbose_name='ステータス')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='質問者')),
                ('best_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_best_answer', to='qa.Answer', verbose_name='ベストアンサー')),
                ('tag', models.ManyToManyField(blank=True, to='qa.Tag', verbose_name='タグ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='対象の質問'),
        ),
    ]
